/**
 * F009 — Visual regression baselines.
 *
 * Captures full-page screenshots against the baselines committed at
 * `tests/screenshots/baseline/*.png` (path configured via
 * `snapshotPathTemplate` in playwright.config.ts).
 *
 * Coverage (BM1-F009 update):
 *   - `dashboard.png`           — authenticated marketer `/dashboard` (F007 refresh)
 *   - `en-knowledge-base.png`   — authenticated `/en/knowledge-base` (F003)
 *   - `en-discovery.png`        — authenticated `/en/discovery` (F004)
 *   - `en-database.png`         — authenticated `/en/database` (F005)
 *   - `en-login.png`            — unauthenticated `/en/login` (BAux1-F004)
 *   - `en-request-access.png`   — unauthenticated `/en/request-access` (BAux1-F004)
 *
 * `/kols/[id]` profile is intentionally omitted here — every row's
 * UUID is non-deterministic across seed runs, so a content-baseline
 * would bake in a specific id that rotates on reseed. The BM1 flow
 * spec exercises the profile page via bm1-flow.spec.ts.
 *
 * Tolerances (per BI1 spec §F009):
 *   - threshold: 0.02    — 2% max normalised per-pixel channel diff
 *   - maxDiffPixels: 2000 — absorbs CI Ubuntu ↔ WSL sub-pixel AA drift
 *
 * Platform policy: Chromium's headless rendering is NOT byte-stable
 * across Linux and macOS (font hinting + subpixel AA differ); pin the
 * suite to Linux (CI + WSL) and skip on macOS/Windows rather than
 * ship a per-platform baseline tree.
 *
 * Regenerate baselines after intentional UI changes (must run on
 * Linux — WSL is fine):
 *   npx playwright test tests/e2e/visual-regression.spec.ts \
 *     --update-snapshots
 */
import { expect, test } from "@playwright/test";

import type { Page } from "@playwright/test";

const MARKETER = {
  email: "marketer@kolmatrix.local",
  password: "KOLM@2026!",
};

async function login(page: Page) {
  await page.goto("/login");
  await page.locator('input[name="email"]').fill(MARKETER.email);
  await page.locator('input[name="password"]').fill(MARKETER.password);
  await page.getByRole("button", { name: /Sign in/ }).click();
  await page.waitForURL(/\/dashboard(\/|$)/);
  await page.waitForLoadState("networkidle").catch(() => {});
}

// BM1-F009 note: the four new authenticated baselines (dashboard
// refresh, knowledge-base, discovery, database) are scaffolded below
// but guarded with test.skip() because generating the baseline PNGs
// requires Playwright's Chromium system libraries (libnspr4, libnss3,
// libasound), which this development box cannot install without sudo.
// CI has those libraries (via `npx playwright install --with-deps`),
// so the baselines can be generated by running:
//   npx playwright test tests/e2e/visual-regression.spec.ts \
//     --update-snapshots
// on the CI runner (or any Linux host with the deps installed) and
// committing the resulting PNGs in `tests/screenshots/baseline/`.
// Unskip each test after the baseline is committed.
const VISUAL_REGRESSION_BASELINES_PENDING = true;

test.describe("Authenticated BM1 visual regression", () => {
  test.skip(
    process.platform !== "linux",
    "Visual regression baseline is Linux-canonical (CI + WSL). Non-Linux runs skip."
  );
  test.skip(
    VISUAL_REGRESSION_BASELINES_PENDING,
    "Baselines pending regeneration — see F009 session notes."
  );

  test("dashboard full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await login(page);
    await page.waitForLoadState("networkidle").catch(() => {});

    // Greeting subtitle bakes in today's date; KPI values roll with
    // seeded counts. Mask the two dynamic regions and let the
    // surrounding chrome (layout, typography, panels) be the signal.
    const dateSubtitle = page.getByText(/Here is your global KOL marketing pulse/);
    const kpiRow = page.getByTestId("dashboard-kpi-row");
    const topKols = page.getByTestId("dashboard-top-kols");

    await expect(page).toHaveScreenshot("dashboard.png", {
      fullPage: true,
      animations: "disabled",
      mask: [dateSubtitle, kpiRow, topKols],
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });

  test("knowledge-base full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await login(page);
    await page
      .locator("aside")
      .getByRole("link", { name: /Knowledge Base/i })
      .click();
    await page.waitForURL(/\/knowledge-base(\/|\?|$)/);
    await page.waitForLoadState("networkidle").catch(() => {});

    // The product grid content rotates with whatever the tenant has
    // saved; mask it so the baseline captures header + recent-activity
    // chrome + empty-state layout.
    const grid = page.getByTestId("kb-grid");

    await expect(page).toHaveScreenshot("en-knowledge-base.png", {
      fullPage: true,
      animations: "disabled",
      mask: [grid],
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });

  test("discovery full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await login(page);
    await page
      .locator("aside")
      .getByRole("link", { name: /KOL Discovery/i })
      .click();
    await page.waitForURL(/\/discovery(\/|\?|$)/);
    await page.waitForLoadState("networkidle").catch(() => {});

    // KOL card content is deterministic given the seed, but avatars
    // use a colour hash that differs per-id, and the summary count is
    // tenant-specific. Mask the grid + summary line; keep the filter
    // sidebar + header layout as the signal.
    const grid = page.getByTestId("discovery-grid");
    const summary = page.getByTestId("discovery-summary");

    await expect(page).toHaveScreenshot("en-discovery.png", {
      fullPage: true,
      animations: "disabled",
      mask: [grid, summary],
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });

  test("database full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await login(page);
    await page
      .locator("aside")
      .getByRole("link", { name: /KOL Database/i })
      .click();
    await page.waitForURL(/\/database(\/|\?|$)/);
    await page.waitForLoadState("networkidle").catch(() => {});

    // Either empty-state or a saved-row table renders here depending
    // on the tenant's isSaved history. Mask both possible containers
    // and keep the filter bar + summary label as the layout signal.
    const table = page.getByTestId("database-table-wrapper");
    const empty = page.getByTestId("database-empty");
    const summary = page.getByTestId("database-summary");

    await expect(page).toHaveScreenshot("en-database.png", {
      fullPage: true,
      animations: "disabled",
      mask: [table, empty, summary],
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });
});

// BAux1-F004 — Authless visual baselines for the cinematic auth pages.
// Both pages are server components rendering i18n-sourced static text
// (LoginBrandOverlay, LoginForm, RequestAccessBrandOverlay,
// RequestAccessForm). No dynamic copy, no CSRF hidden inputs, no
// timestamps — so no mask is required.
test.describe("Auth cinematic — visual regression", () => {
  test.skip(
    process.platform !== "linux",
    "Visual regression baseline is Linux-canonical (CI + WSL). Non-Linux runs skip."
  );

  test("/en/login full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await page.goto("/en/login");
    await page.waitForLoadState("networkidle").catch(() => {});
    await page.evaluate(() => (document as { fonts?: { ready: Promise<unknown> } }).fonts?.ready);

    await expect(page).toHaveScreenshot("en-login.png", {
      fullPage: true,
      animations: "disabled",
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });

  test("/en/request-access full-page screenshot diffs < 2% vs baseline", async ({ page }) => {
    await page.goto("/en/request-access");
    await page.waitForLoadState("networkidle").catch(() => {});
    await page.evaluate(() => (document as { fonts?: { ready: Promise<unknown> } }).fonts?.ready);

    await expect(page).toHaveScreenshot("en-request-access.png", {
      fullPage: true,
      animations: "disabled",
      threshold: 0.02,
      maxDiffPixels: 2000,
    });
  });
});
