/**
 * BL-027-F004 · Pre-commit hook — NETWORK-dependent cases.
 *
 * These two cases run the real regenerate-material-symbols-subset.sh, which
 * fetches a subset from fonts.googleapis.com to compare against the staged
 * woff2 — that fetch is exactly what each case is asserting on, so it can't be
 * mocked away without rewriting the hook itself.
 *
 * BL-094-F001: isolated into `*.network.test.ts` so the default
 * `test:integration` run (and CI's main integration job) stays deterministic.
 * They run in the dedicated `test:integration:network` job
 * (vitest.integration.network.config.ts — serial, retry 2). Root cause of the
 * old flakiness: concurrent Google Fonts subset fetches jittering under the
 * 4-worker integration pool.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { buildDemoFile, makeHookFixture } from "../helpers/pre-commit-hook-fixture";

const fx = makeHookFixture();
beforeEach(() => fx.setup());
afterEach(() => fx.teardown());

describe("BL-027-F004 · Material Symbols pre-commit hook (network)", () => {
  it("icon staged + woff2 matches script output → hook PASS", () => {
    // Touch an existing .tsx-shaped file with an icon callsite. The committed
    // woff2 already covers every icon in the real src/ (we copied the real
    // manifest + woff2). The regen script fetches the same subset from Google
    // Fonts, so before_hash == after_hash and the hook passes via the
    // "already up-to-date" branch.
    fx.stageFile("src/components/Demo.tsx", buildDemoFile());
    // Stage the real woff2 too (simulates Generator running the script and
    // committing alongside the icon change).
    fx.git("add", "src/app/fonts/material-symbols-outlined.woff2");

    const result = fx.runHook();
    expect(result.exitCode, `hook should pass; stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);
    expect(result.stdout).toMatch(/detected Material Symbols icon callsite/);
    // Either branch of the "matches" check is acceptable — what we're proving
    // is that the hook didn't reject.
    expect(result.stdout).toMatch(/up-to-date|matches script output/);
  }, 90_000);

  it("icon staged + woff2 changes but is NOT staged → hook REJECTS with clear message", () => {
    // Drop the woff2 to a known-stale state. The regen script fetches the real
    // subset from Google Fonts (matching the staged manifest), the
    // before_hash != after_hash branch fires, and since we never `git add` the
    // woff2 the hook should reject.
    writeFileSync(
      join(fx.workdir, "src/app/fonts/material-symbols-outlined.woff2"),
      "stale-placeholder-bytes",
    );

    fx.stageFile("src/components/Demo.tsx", buildDemoFile());
    // Intentionally do NOT stage src/app/fonts/material-symbols-outlined.woff2.

    const result = fx.runHook();
    expect(result.exitCode, "hook should reject when woff2 was regenerated but not staged").not.toBe(0);
    expect(result.stdout).toMatch(/woff2 was regenerated by the script but is NOT staged/);
    expect(result.stdout).toMatch(/git add src\/app\/fonts\/material-symbols-outlined\.woff2/);
  }, 90_000);
});
